package com.vm.eea.application.project.addProject

import com.vm.eea.application.*
data class NewProject(val code:String,
                      val description: String,
                      val unitOfOfVoltage: Voltage.Unit,
                      val unitOfPower: Power.Unit,
                      val unitOfLength: Length.Unit,
                      val unitOfTemperature: UnitOfTemperature,
                      val unitOfWireSize: UnitOfWireSize,
                      val singlePhaseVoltage: Double,
                      val twoPhaseVoltage: Double,
                      val threePhaseVoltage: Double,
                      val altitude: Length,
                      val methodOfInstallation: MethodOfInstallation,
                      val ambientTemperature: Temperature,
                      val groundTemperature: Temperature,
                      val soilResistivity: ThermalResistivity,
                      val conductor: Conductor,
                      val insulation: Insulation,
                      val singlePhaseCosPhi: CosPhi,
                      val twoPhaseCosPhi: CosPhi,
                      val threePhaseCosPhi: CosPhi,
                      val panelToPanelMaxVoltDrop: VoltDrop,
                      val panelToMotorMaxVoltDrop: VoltDrop,
                      val circuitInTheSameConduit: CircuitCount,
                      val maxWireSize: WireSize,
                      val minWireSize: WireSize,
                      val standard: Standard,
                      )